version: "{build}"

platform: x64

branches:
  only:
    - master

skip_tags: true

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7
  APM_TEST_PACKAGES: go-config go-get
  ATOM_LINT_WITH_BUNDLED_NODE: "false"

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - mkdir c:\gopath
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - ps: Install-Product node 6

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/joefitzgerald/ci/go-plus/build-package.ps1'))

test: off
deploy: off
